from pathlib import Path

from build_v8m_candidate import default_tag, patch_conf, prepare_context


def test_default_tag_encodes_confidence():
    assert default_tag(0.4) == "v8m-ft-ep1-conf040"
    assert default_tag(0.55) == "v8m-ft-ep1-conf055"


def test_patch_conf_replaces_single_assignment():
    source = "_CONF = 0.40          # old\n_IOU = 0.45\n"
    patched = patch_conf(source, 0.35)
    assert "_CONF = 0.35" in patched
    assert "_IOU = 0.45" in patched


def test_prepare_context_copies_candidate_files(tmp_path, monkeypatch):
    import build_v8m_candidate

    archive = tmp_path / "archive"
    archive.mkdir()
    (archive / "Dockerfile").write_text("FROM scratch\n")
    (archive / "cv_server.py").write_text("print('server')\n")
    (archive / "cv_manager.py").write_text("_CONF = 0.40\n")
    weights = tmp_path / "weights.pt"
    weights.write_bytes(b"weights")
    monkeypatch.setattr(build_v8m_candidate, "ARCHIVE_BUILD", archive)

    dest = tmp_path / "context"
    prepare_context(dest, 0.5, Path(weights))

    assert (dest / "Dockerfile").read_text() == "FROM scratch\n"
    assert (dest / "best.pt").read_bytes() == b"weights"
    assert (dest / "cv_manager.py").read_text() == (
        "_CONF = 0.50          # generated by finetune/build_v8m_candidate.py\n"
    )
