"""hex grid math: axial coordinates with pointy-top orientation and wrapping"""

from __future__ import annotations

import heapq
from dataclasses import dataclass
from typing import Iterator


@dataclass(frozen=True, order=True)
class HexCoord:
    q: int
    r: int

    @property
    def s(self) -> int:
        return -self.q - self.r

    def __add__(self, other: HexCoord) -> HexCoord:
        return HexCoord(self.q + other.q, self.r + other.r)

    def __sub__(self, other: HexCoord) -> HexCoord:
        return HexCoord(self.q - other.q, self.r - other.r)

    def __repr__(self) -> str:
        return f"H({self.q},{self.r})"


# pointy-top axial direction vectors
_DIRECTIONS: tuple[HexCoord, ...] = (
    HexCoord(1, 0),
    HexCoord(1, -1),
    HexCoord(0, -1),
    HexCoord(-1, 0),
    HexCoord(-1, 1),
    HexCoord(0, 1),
)


class HexGrid:
    """wrapping hex grid using axial coordinates with offset-row bijection.

    the bijection used: q_offset = q + r // 2
    this maps pointy-top axial coords onto a rectangular offset grid that
    wraps cleanly on both axes.
    """

    def __init__(self, width: int, height: int) -> None:
        self.width = width
        self.height = height

    def wrap(self, coord: HexCoord) -> HexCoord:
        """normalise a coord to its canonical wrapped form.

        Reduction is performed modulo the torus lattice generated by the same
        two translation vectors used by ``distance``/``line``:
            v1 = (W, 0)          — horizontal wrap
            v2 = (-(H // 2), H)   — vertical wrap (hex torus, not a cylinder)
        The vertical step shifts ``q`` by the CONSTANT ``H // 2`` whenever ``r``
        crosses a top/bottom edge. Using a constant shift (rather than the
        parity-dependent ``r // 2`` offset) is what keeps the neighbour graph
        symmetric and ``distance`` consistent on odd-height maps — otherwise the
        seam between row 0 and row H-1 is off by one for odd H.
        """
        pq = -(self.height // 2)
        n = coord.r // self.height  # number of vertical wraps (floor)
        r = coord.r - n * self.height  # canonical row in [0, H)
        q = coord.q - n * pq  # apply the constant vertical column shift
        # horizontal reduction: keep the offset column q + r//2 inside [0, W)
        q_off = q + r // 2
        q -= (q_off // self.width) * self.width
        return HexCoord(q, r)

    def neighbors(self, coord: HexCoord) -> list[HexCoord]:
        return [self.wrap(coord + d) for d in _DIRECTIONS]

    def _translation_offsets(self) -> list[tuple[int, int]]:
        """the 9 lattice translations to check for minimum distance.

        the two fundamental translation vectors for this wrapping scheme are:
          v1 = (W, 0)          — horizontal wrap
          v2 = (-H//2, H)      — vertical wrap (hex torus, not simple cylinder)
        we check all combinations m*v1 + n*v2 for m,n in {-1,0,1}.
        """
        v1q, v1r = self.width, 0
        v2q, v2r = -(self.height // 2), self.height
        return [
            (m * v1q + n * v2q, m * v1r + n * v2r)
            for m in (-1, 0, 1)
            for n in (-1, 0, 1)
        ]

    def distance(self, a: HexCoord, b: HexCoord) -> int:
        """minimum hex distance accounting for wrapping on both axes"""
        min_dist = 10**9
        for dq, dr in self._translation_offsets():
            c = HexCoord(b.q + dq, b.r + dr)
            d = max(abs(a.q - c.q), abs(a.r - c.r), abs(a.s - c.s))
            min_dist = min(min_dist, d)
        return min_dist

    def all_coords(self) -> Iterator[HexCoord]:
        """iterate every canonical coordinate in the grid"""
        for r in range(self.height):
            for q_off in range(self.width):
                q = q_off - r // 2
                yield HexCoord(q, r)

    def ring(self, center: HexCoord, radius: int) -> list[HexCoord]:
        """all coords exactly `radius` steps from center (wrapping)"""
        if radius == 0:
            return [self.wrap(center)]
        results: list[HexCoord] = []
        # start at the "bottom-left" of the ring and walk all six sides
        current = self.wrap(center + HexCoord(-radius, radius))
        for i in range(6):
            for _ in range(radius):
                results.append(current)
                current = self.wrap(current + _DIRECTIONS[i])
        return results

    def disk(self, center: HexCoord, radius: int) -> list[HexCoord]:
        """all coords within `radius` steps of center (wrapping), including center.

        uses bfs so wrapping on small grids is handled correctly regardless of
        whether radius is large relative to map dimensions.
        """
        canonical_center = self.wrap(center)
        result = [canonical_center]
        visited: set[HexCoord] = {canonical_center}
        frontier = [canonical_center]
        for _ in range(radius):
            next_frontier: list[HexCoord] = []
            for coord in frontier:
                for nb in self.neighbors(coord):
                    if nb not in visited:
                        visited.add(nb)
                        result.append(nb)
                        next_frontier.append(nb)
            frontier = next_frontier
        return result

    def line(self, a: HexCoord, b: HexCoord) -> list[HexCoord]:
        """hex line from a to b via the shortest wrapping path, inclusive"""
        dist = self.distance(a, b)
        if dist == 0:
            return [a]
        # find the unwrapped b that gives the minimum distance
        best_b = b
        best_d = 10**9
        for dq, dr in self._translation_offsets():
            c = HexCoord(b.q + dq, b.r + dr)
            d = max(abs(a.q - c.q), abs(a.r - c.r), abs(a.s - c.s))
            if d < best_d:
                best_d = d
                best_b = c
        results: list[HexCoord] = []
        for i in range(dist + 1):
            t = i / dist
            # lerp in cube space then round
            fq = a.q + (best_b.q - a.q) * t
            fr = a.r + (best_b.r - a.r) * t
            fs = a.s + (best_b.s - a.s) * t
            results.append(self.wrap(_cube_round(fq, fr, fs)))
        return results

    def reachable(
        self,
        origin: HexCoord,
        movement_points: int,
        movement_cost_fn: dict[HexCoord, int] | None = None,
        blocked: set[HexCoord] | None = None,
    ) -> set[HexCoord]:
        """bfs to find all tiles reachable within movement_points.

        movement_cost_fn maps coord → cost to enter that tile (default 1).
        blocked tiles cannot be entered.
        """
        costs = movement_cost_fn or {}
        blocked = blocked or set()
        visited: dict[HexCoord, int] = {origin: 0}
        frontier = [(0, origin)]
        while frontier:
            cost, coord = heapq.heappop(frontier)
            if cost > visited.get(coord, 10**9):
                continue
            for nb in self.neighbors(coord):
                if nb in blocked:
                    continue
                step_cost = costs.get(nb, 1)
                new_cost = cost + step_cost
                if new_cost <= movement_points and new_cost < visited.get(nb, 10**9):
                    visited[nb] = new_cost
                    heapq.heappush(frontier, (new_cost, nb))
        visited.pop(origin)
        return set(visited.keys())

    def shortest_path(
        self,
        origin: HexCoord,
        target: HexCoord,
        movement_cost_fn: dict[HexCoord, int] | None = None,
        blocked: set[HexCoord] | None = None,
    ) -> list[HexCoord] | None:
        """a* shortest path from origin to target (wrapping).

        returns list of coords from origin to target inclusive, or None if unreachable.
        blocked tiles cannot be traversed.
        """
        costs = movement_cost_fn or {}
        blocked = blocked or set()

        g: dict[HexCoord, int] = {origin: 0}
        prev: dict[HexCoord, HexCoord] = {}
        heap: list[tuple[int, HexCoord]] = [(0, origin)]

        while heap:
            _, current = heapq.heappop(heap)
            if current == target:
                path: list[HexCoord] = []
                while current in prev:
                    path.append(current)
                    current = prev[current]
                path.append(origin)
                path.reverse()
                return path
            for nb in self.neighbors(current):
                if nb in blocked:
                    continue
                step_cost = costs.get(nb, 1)
                new_g = g[current] + step_cost
                if new_g < g.get(nb, 10**9):
                    g[nb] = new_g
                    prev[nb] = current
                    h = self.distance(nb, target)
                    heapq.heappush(heap, (new_g + h, nb))
        return None

    def line_of_sight(
        self,
        origin: HexCoord,
        target: HexCoord,
        opaque: set[HexCoord],
    ) -> bool:
        """true if there is an unobstructed line from origin to target.

        opaque is the set of tiles that block vision (e.g. elevated terrain
        when observer is at lower elevation). the endpoints are not blocked
        by themselves.
        """
        path = self.line(origin, target)
        # exclude endpoints from obstruction check
        for coord in path[1:-1]:
            if coord in opaque:
                return False
        return True


def _cube_round(fq: float, fr: float, fs: float) -> HexCoord:
    """round fractional cube coordinates to the nearest hex"""
    q = round(fq)
    r = round(fr)
    s = round(fs)
    dq = abs(q - fq)
    dr = abs(r - fr)
    ds = abs(s - fs)
    if dq > dr and dq > ds:
        q = -r - s
    elif dr > ds:
        r = -q - s
    return HexCoord(q, r)


def axial_to_pixel(coord: HexCoord, size: float) -> tuple[float, float]:
    """convert axial hex coord to pixel centre for pointy-top hexagons.

    size is the distance from centre to vertex.
    """
    x = size * (3**0.5 * coord.q + 3**0.5 / 2 * coord.r)
    y = size * (3 / 2 * coord.r)
    return x, y


def pixel_to_axial(x: float, y: float, size: float) -> HexCoord:
    """convert pixel coords back to the nearest axial hex (no wrapping)"""
    q = (3**0.5 / 3 * x - 1 / 3 * y) / size
    r = (2 / 3 * y) / size
    s = -q - r
    return _cube_round(q, r, s)
