"""Build a lean Docker image for a v8m-style checkpoint.

This intentionally does not reuse the repo's older slim Dockerfiles. It keeps
the proven ``archive/ab_build`` serving code, but installs only the packages
needed for Ultralytics inference + FastAPI serving on top of the PyTorch CUDA
runtime image.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import subprocess
import tempfile
from pathlib import Path


REPO_CV = Path(__file__).resolve().parent.parent
ARCHIVE_BUILD = REPO_CV / "archive" / "ab_build"
REGISTRY_REPO = (
    "asia-southeast1-docker.pkg.dev/til-ai-2026/"
    "repo-til-26-nobrainnohack/nobrainnohack-cv"
)

DOCKERFILE = """\
FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    YOLO_CONFIG_DIR=/tmp/Ultralytics

WORKDIR /workspace

RUN apt-get update \\
 && apt-get install -y --no-install-recommends libgl1 libglib2.0-0 \\
 && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --no-cache-dir --upgrade pip \\
 && python -m pip install --no-cache-dir \\
        opencv-python-headless==4.10.0.84 \\
        pillow==11.0.0 \\
        pyyaml requests scipy tqdm psutil py-cpuinfo \\
        ultralytics-thop \\
        fastapi==0.115.12 \\
        "uvicorn[standard]==0.34.2" \\
 && python -m pip install --no-cache-dir --no-deps ultralytics==8.4.50 \\
 && rm -rf /root/.cache /tmp/*

COPY cv_manager.py cv_server.py ./
COPY best.pt ./best.pt

EXPOSE 5002
CMD ["uvicorn", "cv_server:app", "--port", "5002", "--host", "0.0.0.0"]
"""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def patch_conf(source: str, conf: float) -> str:
    patched, count = re.subn(
        r"^_CONF\s*=\s*[0-9.]+.*$",
        f"_CONF = {conf:.2f}          # generated by finetune/build_v8m_slim_candidate.py",
        source,
        count=1,
        flags=re.MULTILINE,
    )
    if count != 1:
        raise ValueError("could not find exactly one _CONF assignment")
    return patched


def prepare_context(dest: Path, conf: float, weights: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "Dockerfile").write_text(DOCKERFILE)
    shutil.copy2(ARCHIVE_BUILD / "cv_server.py", dest / "cv_server.py")
    (dest / "cv_manager.py").write_text(
        patch_conf((ARCHIVE_BUILD / "cv_manager.py").read_text(), conf)
    )
    shutil.copy2(weights, dest / "best.pt")


def build_image(tag: str, conf: float, weights: Path, registry_tag: bool) -> None:
    with tempfile.TemporaryDirectory(prefix="v8m-slim-candidate-") as tmp:
        context = Path(tmp)
        prepare_context(context, conf, weights)
        local_image = f"nobrainnohack-cv:{tag}"
        subprocess.run(["docker", "build", "-t", local_image, str(context)], check=True)
        if registry_tag:
            subprocess.run(["docker", "tag", local_image, f"{REGISTRY_REPO}:{tag}"], check=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--weights", type=Path, required=True)
    parser.add_argument("--conf", type=float, default=0.40)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--expect-hash", default="")
    parser.add_argument("--no-registry-tag", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    weights = args.weights.resolve()
    if not weights.exists():
        raise FileNotFoundError(weights)
    actual_hash = sha256_file(weights)
    if args.expect_hash and actual_hash != args.expect_hash:
        raise SystemExit(
            f"{weights} hash mismatch:\n"
            f"  got      {actual_hash}\n"
            f"  expected {args.expect_hash}"
        )
    print(f"[v8m-slim-build] weights: {weights}")
    print(f"[v8m-slim-build] sha256:  {actual_hash}")
    print(f"[v8m-slim-build] conf:    {args.conf:.2f}")
    print(f"[v8m-slim-build] tag:     {args.tag}")
    build_image(args.tag, args.conf, weights, registry_tag=not args.no_registry_tag)


if __name__ == "__main__":
    main()
