"""Build the slim Docker image for the 5-model nano ensemble.

Reuses the proven slim base from build_v8m_slim_candidate.py: PyTorch CUDA
runtime + minimal pip deps. Bakes in 5 PT weights, ensemble_conf.json, the
ensemble cv_manager + cv_server, and src/ensemble.py.

Usage:
    python build_ensemble.py \\
        --m1 ../finetune/runs/M1_yolov8n_R1_light/weights/epoch12.pt \\
        --m2 .../epoch27.pt \\
        --m3 .../epoch27.pt \\
        --m4 .../epoch27.pt \\
        --m5 .../epoch4.pt \\
        --conf-json ../src/weights/ensemble_conf.json \\
        --imgsz 1280 \\
        --k 3 \\
        --tag ensemble-v1
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

REPO_CV = Path(__file__).resolve().parent.parent
ARCHIVE_BUILD = REPO_CV / "archive" / "ensemble_build"
SRC = REPO_CV / "src"
REGISTRY_REPO = (
    "asia-southeast1-docker.pkg.dev/til-ai-2026/"
    "repo-til-26-nobrainnohack/nobrainnohack-cv"
)

DOCKERFILE = """\
FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    YOLO_CONFIG_DIR=/tmp/Ultralytics

WORKDIR /workspace

RUN apt-get update \\
 && apt-get install -y --no-install-recommends libgl1 libglib2.0-0 \\
 && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --no-cache-dir --upgrade pip \\
 && python -m pip install --no-cache-dir \\
        opencv-python-headless==4.10.0.84 \\
        pillow==11.0.0 \\
        pyyaml requests scipy tqdm psutil py-cpuinfo \\
        ultralytics-thop \\
        fastapi==0.115.12 \\
        "uvicorn[standard]==0.34.2" \\
 && python -m pip install --no-cache-dir --no-deps ultralytics==8.4.50 \\
 && rm -rf /root/.cache /tmp/*

COPY cv_manager.py cv_server.py ensemble.py ./
COPY ensemble_conf.json ./
COPY m1.pt m2.pt m3.pt m4.pt m5.pt ./

EXPOSE 5002
CMD ["uvicorn", "cv_server:app", "--port", "5002", "--host", "0.0.0.0"]
"""


def patch_value(source: str, name: str, value: str) -> str:
    patched, count = re.subn(
        rf"^{re.escape(name)}\s*=\s*.*$",
        f"{name} = {value}          # generated by build_ensemble.py",
        source,
        count=1,
        flags=re.MULTILINE,
    )
    if count != 1:
        raise ValueError(f"could not find exactly one {name} assignment")
    return patched


def prepare_context(dest: Path, args: argparse.Namespace) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "Dockerfile").write_text(DOCKERFILE)
    shutil.copy2(ARCHIVE_BUILD / "cv_server.py", dest / "cv_server.py")
    shutil.copy2(SRC / "ensemble.py", dest / "ensemble.py")
    shutil.copy2(args.conf_json, dest / "ensemble_conf.json")

    src = (ARCHIVE_BUILD / "cv_manager.py").read_text()
    src = patch_value(src, "_IMGSZ", str(args.imgsz))
    src = patch_value(src, "_RECT", "True" if args.rect else "False")
    src = patch_value(src, "_K", str(args.k))
    (dest / "cv_manager.py").write_text(src)

    for i, wpath in enumerate([args.m1, args.m2, args.m3, args.m4, args.m5], 1):
        if not wpath.exists():
            raise SystemExit(f"missing weights: {wpath}")
        shutil.copy2(wpath, dest / f"m{i}.pt")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    for slot in ("m1", "m2", "m3", "m4", "m5"):
        p.add_argument(f"--{slot}", type=Path, required=True)
    p.add_argument("--conf-json", type=Path, required=True)
    p.add_argument("--imgsz", type=int, default=1280)
    p.add_argument("--rect", action="store_true")
    p.add_argument("--k", type=int, default=3)
    p.add_argument("--tag", required=True)
    p.add_argument("--no-registry-tag", action="store_true")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    with tempfile.TemporaryDirectory(prefix="ensemble-build-") as tmp:
        context = Path(tmp)
        prepare_context(context, args)
        local_image = f"nobrainnohack-cv:{args.tag}"
        print(f"[ensemble-build] context: {context}")
        print(f"[ensemble-build] tag:     {args.tag}")
        subprocess.run(["docker", "build", "-t", local_image, str(context)], check=True)
        if not args.no_registry_tag:
            subprocess.run(["docker", "tag", local_image, f"{REGISTRY_REPO}:{args.tag}"], check=True)


if __name__ == "__main__":
    main()
