"""Build confidence-tuned Docker images for the real v8m ep1 checkpoint.

This keeps ``archive/ab_build`` immutable: a temporary build context is created
with the requested confidence and checkpoint, then passed to ``docker build``.

Examples:
    python finetune/build_v8m_candidate.py --conf 0.45
    python finetune/build_v8m_candidate.py --conf 0.50 --tag v8m-ft-ep1-conf050
"""
from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import subprocess
import tempfile
from pathlib import Path


REPO_CV = Path(__file__).resolve().parent.parent
ARCHIVE_BUILD = REPO_CV / "archive" / "ab_build"
DEFAULT_WEIGHTS = REPO_CV / "src" / "weights" / "best_v8m_ep1.pt"
BASELINE_HASH = "d10400fb8287364b8ba849cbf2a940213d038cb63ecb620fdf4b6140d81e8d58"
REGISTRY_REPO = (
    "asia-southeast1-docker.pkg.dev/til-ai-2026/"
    "repo-til-26-nobrainnohack/nobrainnohack-cv"
)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def default_tag(conf: float) -> str:
    return f"v8m-ft-ep1-conf{int(round(conf * 100)):03d}"


def patch_conf(source: str, conf: float) -> str:
    patched, count = re.subn(
        r"^_CONF\s*=\s*[0-9.]+.*$",
        f"_CONF = {conf:.2f}          # generated by finetune/build_v8m_candidate.py",
        source,
        count=1,
        flags=re.MULTILINE,
    )
    if count != 1:
        raise ValueError("could not find exactly one _CONF assignment")
    return patched


def prepare_context(dest: Path, conf: float, weights: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    for name in ("Dockerfile", "cv_server.py"):
        shutil.copy2(ARCHIVE_BUILD / name, dest / name)
    (dest / "cv_manager.py").write_text(
        patch_conf((ARCHIVE_BUILD / "cv_manager.py").read_text(), conf)
    )
    shutil.copy2(weights, dest / "best.pt")


def build_image(tag: str, conf: float, weights: Path, registry_tag: bool) -> None:
    with tempfile.TemporaryDirectory(prefix="v8m-candidate-") as tmp:
        context = Path(tmp)
        prepare_context(context, conf, weights)
        local_image = f"nobrainnohack-cv:{tag}"
        subprocess.run(["docker", "build", "-t", local_image, str(context)], check=True)
        if registry_tag:
            subprocess.run(["docker", "tag", local_image, f"{REGISTRY_REPO}:{tag}"], check=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--conf", type=float, required=True)
    parser.add_argument("--tag", help="Docker tag; defaults to v8m-ft-ep1-confXYZ")
    parser.add_argument("--weights", type=Path, default=DEFAULT_WEIGHTS)
    parser.add_argument(
        "--expect-hash",
        default=BASELINE_HASH,
        help="Refuse to build if --weights does not match this sha256. "
        "Use --expect-hash '' for continuation checkpoints.",
    )
    parser.add_argument(
        "--no-registry-tag",
        action="store_true",
        help="Only create nobrainnohack-cv:<tag>, not the Artifact Registry-style tag.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    weights = args.weights.resolve()
    if not weights.exists():
        raise FileNotFoundError(weights)
    actual_hash = sha256_file(weights)
    if args.expect_hash and actual_hash != args.expect_hash:
        raise SystemExit(
            f"{weights} hash mismatch:\n"
            f"  got      {actual_hash}\n"
            f"  expected {args.expect_hash}"
        )
    tag = args.tag or default_tag(args.conf)
    print(f"[v8m-build] weights: {weights}")
    print(f"[v8m-build] sha256:  {actual_hash}")
    print(f"[v8m-build] conf:    {args.conf:.2f}")
    print(f"[v8m-build] tag:     {tag}")
    build_image(tag, args.conf, weights, registry_tag=not args.no_registry_tag)


if __name__ == "__main__":
    main()
