"""Build a lean Docker image for a v8m-style checkpoint with configurable imgsz + rect.

Extends build_v8m_slim_candidate.py with --imgsz and --rect CLI args, and patches
three constants in cv_manager.py (_CONF, _IMGSZ, _RECT) via a generic helper.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import subprocess
import tempfile
from pathlib import Path


REPO_CV = Path(__file__).resolve().parent.parent
ARCHIVE_BUILD = REPO_CV / "archive" / "ab_build"
REGISTRY_REPO = (
    "asia-southeast1-docker.pkg.dev/til-ai-2026/"
    "repo-til-26-nobrainnohack/nobrainnohack-cv"
)

BASELINE_HASH = "d10400fb8287364b8ba849cbf2a940213d038cb63ecb620fdf4b6140d81e8d58"
DEFAULT_WEIGHTS = REPO_CV / "src" / "weights" / "best_v8m_ep1.pt"

DOCKERFILE = """\
FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    YOLO_CONFIG_DIR=/tmp/Ultralytics

WORKDIR /workspace

RUN apt-get update \\
 && apt-get install -y --no-install-recommends libgl1 libglib2.0-0 \\
 && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --no-cache-dir --upgrade pip \\
 && python -m pip install --no-cache-dir \\
        opencv-python-headless==4.10.0.84 \\
        pillow==11.0.0 \\
        pyyaml requests scipy tqdm psutil py-cpuinfo \\
        ultralytics-thop \\
        fastapi==0.115.12 \\
        "uvicorn[standard]==0.34.2" \\
 && python -m pip install --no-cache-dir --no-deps ultralytics==8.4.50 \\
 && rm -rf /root/.cache /tmp/*

COPY cv_manager.py cv_server.py ./
COPY best.pt ./best.pt

EXPOSE 5002
CMD ["uvicorn", "cv_server:app", "--port", "5002", "--host", "0.0.0.0"]
"""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def patch_value(source: str, name: str, value: str) -> str:
    patched, count = re.subn(
        rf"^{re.escape(name)}\s*=\s*.*$",
        f"{name} = {value}          # generated by build_imgsz_candidate.py",
        source,
        count=1,
        flags=re.MULTILINE,
    )
    if count != 1:
        raise ValueError(f"could not find exactly one {name} assignment")
    return patched


def default_tag(conf: float, imgsz: int, rect: bool) -> str:
    return (
        f"v8m-ft-ep1-conf{int(round(conf * 100)):03d}"
        f"-imgsz{imgsz}"
        f"{'-rect' if rect else ''}"
    )


def prepare_context(dest: Path, args: argparse.Namespace, weights: Path) -> None:
    conf = args.conf
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "Dockerfile").write_text(DOCKERFILE)
    shutil.copy2(ARCHIVE_BUILD / "cv_server.py", dest / "cv_server.py")
    src = (ARCHIVE_BUILD / "cv_manager.py").read_text()
    src = patch_value(src, "_CONF", f"{conf:.2f}")
    src = patch_value(src, "_IMGSZ", str(args.imgsz))
    src = patch_value(src, "_RECT", "True" if args.rect else "False")
    (dest / "cv_manager.py").write_text(src)
    shutil.copy2(weights, dest / "best.pt")


def build_image(args: argparse.Namespace, weights: Path) -> None:
    tag = args.tag
    with tempfile.TemporaryDirectory(prefix="imgsz-candidate-") as tmp:
        context = Path(tmp)
        prepare_context(context, args, weights)
        local_image = f"nobrainnohack-cv:{tag}"
        subprocess.run(["docker", "build", "-t", local_image, str(context)], check=True)
        if not args.no_registry_tag:
            subprocess.run(
                ["docker", "tag", local_image, f"{REGISTRY_REPO}:{tag}"],
                check=True,
            )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a v8m candidate image with configurable conf, imgsz, and rect."
    )
    parser.add_argument("--weights", type=Path, default=DEFAULT_WEIGHTS)
    parser.add_argument("--conf", type=float, default=0.40)
    parser.add_argument("--imgsz", type=int, default=1280)
    parser.add_argument(
        "--rect",
        action="store_true",
        help="patch _RECT = True in cv_manager.py",
    )
    parser.add_argument("--tag", default=None)
    parser.add_argument(
        "--expect-hash",
        default=BASELINE_HASH,
        help="Refuse to build if --weights does not match this sha256. "
             "Use --expect-hash '' for continuation checkpoints.",
    )
    parser.add_argument("--no-registry-tag", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    weights = args.weights.resolve()
    if not weights.exists():
        raise FileNotFoundError(weights)
    actual_hash = sha256_file(weights)
    if args.expect_hash and actual_hash != args.expect_hash:
        raise SystemExit(
            f"{weights} hash mismatch:\n"
            f"  got      {actual_hash}\n"
            f"  expected {args.expect_hash}"
        )
    if args.tag is None:
        args.tag = default_tag(args.conf, args.imgsz, args.rect)
    print(f"[imgsz-build] weights: {weights}")
    print(f"[imgsz-build] sha256:  {actual_hash}")
    print(f"[imgsz-build] conf:    {args.conf:.2f}")
    print(f"[imgsz-build] imgsz:   {args.imgsz}")
    print(f"[imgsz-build] rect:    {args.rect}")
    print(f"[imgsz-build] tag:     {args.tag}")
    build_image(args, weights)


if __name__ == "__main__":
    main()
