"""One-off: build the 2-model M1+M2 test ensemble docker image.

Usage:
    python build_test2.py \\
        --m1 runs/M1_yolov8n_R1_light/weights/epoch12.pt \\
        --m2 runs/M2_yolo11n_R2_heavy_color/weights/epoch27.pt \\
        --tag test2-m1ep12-m2ep27
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

REPO_CV = Path(__file__).resolve().parent.parent
ARCHIVE = REPO_CV / "archive" / "test2_build"
SRC = REPO_CV / "src"

DOCKERFILE = """\
FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    YOLO_CONFIG_DIR=/tmp/Ultralytics

WORKDIR /workspace

RUN apt-get update \\
 && apt-get install -y --no-install-recommends libgl1 libglib2.0-0 \\
 && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --no-cache-dir --upgrade pip \\
 && python -m pip install --no-cache-dir \\
        opencv-python-headless==4.10.0.84 \\
        pillow==11.0.0 \\
        pyyaml requests scipy tqdm psutil py-cpuinfo \\
        ultralytics-thop \\
        fastapi==0.115.12 \\
        "uvicorn[standard]==0.34.2" \\
 && python -m pip install --no-cache-dir --no-deps ultralytics==8.4.50 \\
 && rm -rf /root/.cache /tmp/*

COPY cv_manager.py cv_server.py ensemble.py ./
COPY m1.pt m2.pt ./

EXPOSE 5002
CMD ["uvicorn", "cv_server:app", "--port", "5002", "--host", "0.0.0.0"]
"""


def patch_value(source: str, name: str, value: str) -> str:
    patched, count = re.subn(
        rf"^{re.escape(name)}\s*=\s*.*$",
        f"{name} = {value}          # generated by build_test2.py",
        source,
        count=1,
        flags=re.MULTILINE,
    )
    if count != 1:
        raise ValueError(f"could not find exactly one {name} assignment")
    return patched


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--m1", type=Path, required=True)
    p.add_argument("--m2", type=Path, required=True)
    p.add_argument("--conf", type=float, default=0.40)
    p.add_argument("--imgsz", type=int, default=1280)
    p.add_argument("--rect", action="store_true")
    p.add_argument("--k", type=int, default=2)
    p.add_argument("--tag", required=True)
    return p.parse_args()


def main() -> None:
    args = parse_args()
    for w in (args.m1, args.m2):
        if not w.exists():
            raise SystemExit(f"missing weights: {w}")
    with tempfile.TemporaryDirectory(prefix="test2-build-") as tmp:
        ctx = Path(tmp)
        (ctx / "Dockerfile").write_text(DOCKERFILE)
        shutil.copy2(ARCHIVE / "cv_server.py", ctx / "cv_server.py")
        shutil.copy2(SRC / "ensemble.py", ctx / "ensemble.py")
        src = (ARCHIVE / "cv_manager.py").read_text()
        src = patch_value(src, "_CONF", f"{args.conf:.2f}")
        src = patch_value(src, "_IMGSZ", str(args.imgsz))
        src = patch_value(src, "_RECT", "True" if args.rect else "False")
        src = patch_value(src, "_K", str(args.k))
        (ctx / "cv_manager.py").write_text(src)
        shutil.copy2(args.m1, ctx / "m1.pt")
        shutil.copy2(args.m2, ctx / "m2.pt")
        local = f"nobrainnohack-cv:{args.tag}"
        print(f"[test2] tag: {args.tag}")
        print(f"[test2] conf={args.conf} imgsz={args.imgsz} rect={args.rect} k={args.k}")
        subprocess.run(["docker", "build", "-t", local, str(ctx)], check=True)


if __name__ == "__main__":
    main()
