"""Build the phone-home sniffer Docker image.

Reuses best_v8m_ep1.pt + the proven 0.727 inference settings (conf=0.40,
imgsz=1536). Adds per-image diagnostics that post to a webhook in a
background thread — no impact on inference latency or score.

Usage:
    python build_sniffer.py --webhook https://webhook.site/<uuid> \\
        --tag v8m-sniffer-v1
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

REPO_CV = Path(__file__).resolve().parent.parent
ARCHIVE_BUILD = REPO_CV / "archive" / "sniffer_build"
SRC_WEIGHTS = REPO_CV / "src" / "weights" / "best_v8m_ep1.pt"
REGISTRY_REPO = (
    "asia-southeast1-docker.pkg.dev/til-ai-2026/"
    "repo-til-26-nobrainnohack/nobrainnohack-cv"
)

DOCKERFILE = """\
FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    YOLO_CONFIG_DIR=/tmp/Ultralytics

WORKDIR /workspace

RUN apt-get update \\
 && apt-get install -y --no-install-recommends libgl1 libglib2.0-0 \\
 && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --no-cache-dir --upgrade pip \\
 && python -m pip install --no-cache-dir \\
        opencv-python-headless==4.10.0.84 \\
        pillow==11.0.0 \\
        pyyaml requests scipy tqdm psutil py-cpuinfo \\
        ultralytics-thop \\
        fastapi==0.115.12 \\
        "uvicorn[standard]==0.34.2" \\
 && python -m pip install --no-cache-dir --no-deps ultralytics==8.4.50 \\
 && rm -rf /root/.cache /tmp/*

COPY cv_manager.py cv_server.py ./
COPY best.pt ./best.pt

EXPOSE 5002
CMD ["uvicorn", "cv_server:app", "--port", "5002", "--host", "0.0.0.0"]
"""


def patch_value(source: str, name: str, value: str) -> str:
    patched, count = re.subn(
        rf"^{re.escape(name)}\s*=\s*.*$",
        f"{name} = {value}          # generated by build_sniffer.py",
        source,
        count=1,
        flags=re.MULTILINE,
    )
    if count != 1:
        raise ValueError(f"could not find exactly one {name} assignment")
    return patched


def prepare_context(dest: Path, args: argparse.Namespace) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "Dockerfile").write_text(DOCKERFILE)
    shutil.copy2(ARCHIVE_BUILD / "cv_server.py", dest / "cv_server.py")
    src = (ARCHIVE_BUILD / "cv_manager.py").read_text()
    src = patch_value(src, "_CONF", f"{args.conf:.2f}")
    src = patch_value(src, "_IMGSZ", str(args.imgsz))
    src = patch_value(src, "_RECT", "True" if args.rect else "False")
    src = patch_value(src, "_WEBHOOK_URL", repr(args.webhook))
    (dest / "cv_manager.py").write_text(src)
    if not args.weights.exists():
        raise SystemExit(f"missing weights: {args.weights}")
    shutil.copy2(args.weights, dest / "best.pt")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--webhook", required=True,
                   help="POST endpoint for diagnostics (e.g. webhook.site URL)")
    p.add_argument("--weights", type=Path, default=SRC_WEIGHTS)
    p.add_argument("--conf", type=float, default=0.40)
    p.add_argument("--imgsz", type=int, default=1536)
    p.add_argument("--rect", action="store_true")
    p.add_argument("--tag", required=True)
    p.add_argument("--no-registry-tag", action="store_true")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    with tempfile.TemporaryDirectory(prefix="sniffer-build-") as tmp:
        context = Path(tmp)
        prepare_context(context, args)
        local_image = f"nobrainnohack-cv:{args.tag}"
        print(f"[sniffer-build] webhook: {args.webhook}")
        print(f"[sniffer-build] conf={args.conf} imgsz={args.imgsz} rect={args.rect}")
        print(f"[sniffer-build] tag:     {args.tag}")
        subprocess.run(["docker", "build", "-t", local_image, str(context)], check=True)
        if not args.no_registry_tag:
            subprocess.run(["docker", "tag", local_image, f"{REGISTRY_REPO}:{args.tag}"], check=True)


if __name__ == "__main__":
    main()
